import sqlite3
import pandas as pd
import numpy as np
from datetime import datetime

DB_PATH = "ludi.db"
OUTPUT_FILE = "WEEK3_VALIDATION_REPORT.md"

def generate_report():
    print(f"Generating {OUTPUT_FILE}...")
    
    conn = sqlite3.connect(DB_PATH)
    
    # Load settled bets
    query = '''
        SELECT *
        FROM bet_recommendations
        WHERE outcome IN ('WIN', 'LOSS', 'PUSH')
    '''
    df = pd.read_sql_query(query, conn)
    
    # Load CLV coverage data
    clv_query = '''
        SELECT COUNT(*) as total, COUNT(clv) as with_clv
        FROM bet_recommendations
    '''
    clv_stats = pd.read_sql_query(clv_query, conn)
    clv_coverage = (clv_stats['with_clv'][0] / clv_stats['total'][0]) * 100 if clv_stats['total'][0] > 0 else 0
    
    conn.close()
    
    if df.empty:
        print("❌ No settled bets found. Cannot generate validation report.")
        return

    # METRICS CALCULATION
    total_bets = len(df)
    wins = len(df[df['outcome'] == 'WIN'])
    losses = len(df[df['outcome'] == 'LOSS'])
    pushes = len(df[df['outcome'] == 'PUSH'])
    hit_rate = (wins / (wins + losses)) * 100 if (wins + losses) > 0 else 0
    pnl = df['profit_loss'].sum()
    roi = (pnl / df['units'].sum()) * 100 if df['units'].sum() > 0 else 0
    
    df['error_sq'] = (df['actual_result'] - df['projection']) ** 2
    rmse = np.sqrt(df['error_sq'].mean())
    
    # CLV Analysis
    df_clv = df.dropna(subset=['clv'])
    clv_diff = (df_clv['clv'] - df_clv['line']).mean() # Positive means line moved in our favor (roughly)
    
    # GO/NO-GO LOGIC
    # Success Criteria: Hit Rate > 52%, RMSE < 10% (approx < 2.0 for NBA props), CLV Coverage > 80% (new requirement)
    # Note: RMSE < 10% is tricky for mixed stats (PTS vs AST). Typically RMSE < 3.0 is good for props.
    
    status_emoji = "🟢 GO"
    recommendation = "Proceed to Week 4 (Calibration)"
    
    if hit_rate < 50.0:
        status_emoji = "🔴 NO-GO"
        recommendation = "CRITICAL: Extend Calibration Phase. Hit rate below breakeven."
    elif hit_rate < 52.4:
        status_emoji = "🟡 CAUTION"
        recommendation = "Proceed with Caution. Hit rate marginal."
        
    md = f"""# Ludi Informatio - Week 3 Validation Report
**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Status:** {status_emoji}
**Recommendation:** {recommendation}

---

## 1. Executive Summary

| Metric | Result | Target | Status |
|--------|--------|--------|--------|
| **Total Bets Settled** | {total_bets} | 50+ | {'✅' if total_bets >= 50 else '❌'} |
| **Hit Rate** | {hit_rate:.1f}% | > 52.4% | {status_emoji} |
| **ROI** | {roi:+.1f}% | > 0% | {'✅' if roi > 0 else '❌'} |
| **RMSE (Error)** | {rmse:.2f} | < 3.0 | {'✅' if rmse < 3.0 else '❌'} |
| **CLV Coverage** | {clv_coverage:.1f}% | > 80% | {'✅' if clv_coverage > 80 else '⚠️'} |

---

## 2. Performance Breakdown

### By Archetype
"""

    if 'archetype' in df.columns:
        arch_stats = df.groupby('archetype').apply(
            lambda x: pd.Series({
                'Bets': len(x),
                'Hit Rate': f"{(len(x[x['outcome']=='WIN']) / len(x[x['outcome']!='PUSH'])) * 100:.1f}%" if len(x[x['outcome']!='PUSH']) > 0 else '0.0%',
                'PnL': f"{x['profit_loss'].sum():+.2f}u",
                'Avg Error': f"{(x['actual_result'] - x['projection']).abs().mean():.2f}"
            })
        ).sort_values('Bets', ascending=False)
        md += arch_stats.to_markdown() + "\n\n"

    md += "### By Stat Category\n"
    stat_stats = df.groupby('stat_category').apply(
        lambda x: pd.Series({
            'Bets': len(x),
            'Hit Rate': f"{(len(x[x['outcome']=='WIN']) / len(x[x['outcome']!='PUSH'])) * 100:.1f}%" if len(x[x['outcome']!='PUSH']) > 0 else '0.0%',
            'RMSE': f"{np.sqrt(((x['actual_result'] - x['projection']) ** 2).mean()):.2f}"
        })
    ).sort_values('Bets', ascending=False)
    md += stat_stats.to_markdown() + "\n\n"
    
    md += f"""---
## 3. Recommendations & Next Steps

1. **Calibration Focus**: Identify archetypes with high error (RMSE > 3.0) and adjust `module_e.py` modifiers.
2. **Missing Data**: Ensure we have game logs for all pending bets. Current pending: {clv_stats['total'][0] - total_bets}.
3. **CLV Check**: We have {clv_stats['with_clv'][0]} bets with Closing Line Value data. {clv_stats['total'][0] - clv_stats['with_clv'][0]} are missing.

*Generated by Ludi Valdidation Engine*
"""

    with open(OUTPUT_FILE, "w") as f:
        f.write(md)
        
    print(f"✅ Report saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_report()
